modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
logoFile = "${mod_logo}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_link}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "alexsmobs"
    mandatory = true
    versionRange = "${alexs_mobs_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "better_campfires"
    mandatory = true
    versionRange = "${build_your_campfire_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "burnt"
    mandatory = true
    versionRange = "${burnt_basic_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "cloth_config"
    mandatory = true
    versionRange = "${cloth_config_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "curios"
    mandatory = true
    versionRange = "${curios_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "deeperdarker"
    mandatory = true
    versionRange = "${deeper_and_darker_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "diet"
    mandatory = true
    versionRange = "${diet_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "dungeons_plus"
    mandatory = true
    versionRange = "${dungeons_plus_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "eanimod"
    mandatory = true
    versionRange = "${genetic_animals_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "guardvillagers"
    mandatory = true
    versionRange = "${guard_villagers_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "passablefoliage"
    mandatory = true
    versionRange = "${passable_foliage_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "sanitydim"
    mandatory = true
    versionRange = "${sanity_dim_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "simplefarming"
    mandatory = true
    versionRange = "${simple_farming_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "sound_physics_remastered"
    mandatory = true
    versionRange = "${sound_physics_remastered_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "toughasnails"
    mandatory = true
    versionRange = "${tough_as_nails_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "voicechat"
    mandatory = true
    versionRange = "${simple_voice_chat_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "weather2"
    mandatory = true
    versionRange = "${weather2_version_range}"
    ordering = "NONE"
    side = "BOTH"