modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
logoFile = "${mod_logo}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_link}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "better_campfires"
    mandatory = false
    versionRange = "${build_your_campfire_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "burnt"
    mandatory = false
    versionRange = "${burnt_basic_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "diet"
    mandatory = false
    versionRange = "${diet_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "dungeons_plus"
    mandatory = false
    versionRange = "${dungeons_plus_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "guardvillagers"
    mandatory = false
    versionRange = "${guard_villagers_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "realistictorches"
    mandatory = false
    versionRange = "${realistic_torches_version_range}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "sanitydim"
    mandatory = false
    versionRange = "${sanity_dim_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "weather2"
    mandatory = false
    versionRange = "${weather2_version_range}"
    ordering = "NONE"
    side = "BOTH"